package johanna;

/**
 *
 * @author JAIRO CASTILLO
 */
public class Johanna {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        System.out.println("Hola Mundo");
    }
    
}
